name: "Collect Metadata"

on:
  push:
    branches:
      - "main"

jobs:
  collect:
    name: "Collect Metadata"
    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: "Install dependencies"
        run: pdm install

      - name: print secrets
        env:
          COOKIES: ${{secrets.COOKIES}}
        shell: bash
        run: echo "$COOKIES" >> cookies.txt

      - name: "Run slabvis"
        run: pdm run get_metadata

      - name: Push version changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "downloaded metadata"
          branch: ${{ github.event.repository.default_branch }}
